name: my_rabai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.15.0
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3
  go_router: ^17.3.0
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.3.2
  phosphor_flutter: ^2.1.0
  file_picker: ^3.0.4
  image_picker: ^1.2.2
  intl: ^0.20.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # Properly added here inside dev_dependencies

flutter:
  uses-material-design: true

  # Asset registration bundle configuration
  assets:
    - assets/
    - assets/images/

# Global configuration for the icon generator (unindented to the far left)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"